import type { Metadata } from "next";
import { Geist, Geist_Mono, Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sections/header";
import Footer from "@/components/sections/footer";
import { AuthProvider } from "@/context/AuthContext";
import LayoutWrapper from "@/components/layoutwrapper/layoutwrapper";
import { cookies } from "next/headers";
import { AuthProviderLanding } from "@/context/AuthContextLanding";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Schibsted_Grotesk({
  weight: "400",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const authToken = cookieStore.get("seo-auth-token")?.value;

  let initialUser = null;
  if (authToken) {
    try {
      const decoded = JSON.parse(
        Buffer.from(authToken, "base64").toString()
      );
      if (decoded.exp > Date.now()) {
        initialUser = {
          id: decoded.id,
          name: decoded.name,
          email: decoded.email,
          role: decoded.role,
        };
      }
    } catch {
      initialUser = null;
    }
  }
  return (
    <html
      lang="en"
      className={`${poppins.className}`}
    >

      <body className="">
       {/*  <AuthProvider> */}
          <AuthProviderLanding initialUser={initialUser}>
          <div className=" bg-[var(--bg-secondary)]">

            <LayoutWrapper>
              {children}

            </LayoutWrapper>
          </div>
          </AuthProviderLanding>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
